server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  hikari:
    minimum-idle: 5
    maximum-pool-size: 10
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 20000

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 10
        connection-timeout: 60000
        requested-heartbeat: 30

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true # Mostra as queries no log
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        packages-to-scan: com.ambev.order.domain

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
